### ISSUE TITLE
Use fast-syntax-highlighting over zsh-syntax-highlighting

### ISSUE THREAD

**Issue by vladdoster** [acullenhms/dotfiles#1]
I see you use `zsh`. . .

I'd recommend [fast-syntax-highlighting](https://github.com/zdharma/fast-syntax-highlighting) over zsh-syntax-highlighting

**Comment by acullenhms** [comment]
Ooh I'll check this out. That bracket highlighting seems nice

On May 16, 2020 1:06 AM, Vlad Doster <notifications@github.com> wrote:

I see you use zsh. . .

I'd recommend fast-syntax-highlighting<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_zdharma_fast-2Dsyntax-2Dhighlighting&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=DBGksm_Nrehm4d_t0qZSZPW797rJ8-fmFPYFdIcP2PQ&m=0BZx6Ie5ManPXY2d6d41GDne0CcIE42VfxOZqzQ7DDE&s=RHT9N_ch8kOAb-QzrgY1xhoXhM_alZKGZ6q1z7e8g3w&e=> over zsh-syntax-highlighting
